[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.17'

via_ir = true
optimizer = true
optimizer_runs = 200

# 添加显式重映射
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    'permit2/=lib/permit2/'
]
