[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.remappings]
"@openzeppelin/" = "lib/openzeppelin-contracts/"

# 添加RPC端点和Etherscan配置
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
